### PR TITLE
Add Atomberg fan

### PR DESCRIPTION
**Pull request by tanishqmanuja**
Manufacturer: Atomberg
Model: Studio+

https://atomberg.com/atomberg-studio-plus-bldc-motor-with-remote-3-blade-ceiling-fan

### CODE REVIEW

**Comment by litinoveweedle** [comment]
Hello, please would you be so kind to merge your PR with the updated master and remove update of the docs? Those are now generated automatically

**Comment by tanishqmanuja** [comment]
Surely, will do today

**Comment by tanishqmanuja** [comment]
Hi, not related to this. Should we consider moving test_data.py to a scripts folder like convention in other projects. Also that way root folder will not be cluttered if we add more checking scripts in the future

**Comment by tanishqmanuja** [comment]
Action is unable to checkout branch 😔 

Refer: https://github.com/actions/checkout/issues/1108

**Comment by tanishqmanuja** [comment]
Looks like the action for some reason uses wrong fetch command

IN THIS PR

https://github.com/litinoveweedle/SmartIR/actions/runs/9851040948/job/27197230238?pr=48#step:2:54
```sh
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
```

IN PR 46

https://github.com/litinoveweedle/SmartIR/actions/runs/9682653449/job/27184216327?pr=46#step:2:51
```sh
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +2b0b899ce2283c6e26410880547ccec0c1e4ffbf:refs/remotes/pull/46/merge
```

**Comment by litinoveweedle** [comment]
> Looks like the action for some reason uses wrong fetch command
> 
> IN THIS PR
> 
> https://github.com/litinoveweedle/SmartIR/actions/runs/9851040948/job/27197230238?pr=48#step:2:54
> 
> ```shell
>   /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
> ```
> 
> IN PR 46
> 
> https://github.com/litinoveweedle/SmartIR/actions/runs/9682653449/job/27184216327?pr=46#step:2:51
> 
> ```shell
>   /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +2b0b899ce2283c6e26410880547ccec0c1e4ffbf:refs/remotes/pull/46/merge
> ```

I know, this issue bash me also on other PR. I have no idea why. I simply use checkout@v4 action, with depth 0. Do you have any idea how to fix this?

**Comment by tanishqmanuja** [comment]
I guess the ref is wrong in workflow

**Comment by litinoveweedle** [comment]
the ref is actually copy paste from the Prettier action examples; https://github.com/marketplace/actions/prettier-action (example 2)

${{ github.ref_name }} shall be name of the current branch in the action context

**Comment by tanishqmanuja** [comment]
Yup but it only works if the ref_name is within the current repo, which is not the case here. Try removing this line once maybe.

**Comment by litinoveweedle** [comment]
This seems to be related to our case: https://github.com/actions/checkout/issues/1108


I need to play with the actions anyway, as another issue is when I use action on PR, which would reformat some of the files and try to commit changes - see here: https://github.com/litinoveweedle/SmartIR/actions/runs/9920136130/job/27407490244

So my proposal would be to move reformat into the action triggered by push, I just didn't want to do such changes over master.

**Comment by litinoveweedle** [comment]
BTW: proposed [solution](https://github.com/0ptim/DeFiChainWiki/blob/main/.github/workflows/testbuild.yml) mentioned above is:

```
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
```

**Comment by litinoveweedle** [comment]
OK, I updated the worflow in the master, but the issue is, that workflow in this PR still points to the [old version](https://github.com/litinoveweedle/SmartIR/actions/runs/9851040948/workflow?pr=48) and I didn't find a way, how to run new workflow against older PR. :-o

**Comment by tanishqmanuja** [comment]
Should i do a new pr ?

**Comment by litinoveweedle** [comment]
> Should i do a new pr ?

I am afraid, that it is only way I know how to use updated action, sorry.

**Comment by tanishqmanuja** [comment]
No worries, i will push tomorrow no big deal 😁

**Comment by tanishqmanuja** [comment]
Moved to https://github.com/litinoveweedle/SmartIR/pull/74

**Pull request closed without merging**
