### PR TITLE
Add codes for Daikin FWT-GT on ESPHome

### PR DESCRIPTION
**Pull request by ripa1993**
Add codes for Daikin FWT-GT on ESPHome

### CODE REVIEW

**Comment by litinoveweedle** [comment]
Hello, thank you for PR, please remove any modifications to the DOCS pages, as those are generated automatically. (docs/CLIMATE_CODES.md)

**Comment by litinoveweedle** [comment]
thanks. In addition you have error in the json:

Invalid climate device JSON file '7100.json': missing or invalid attribute 'temperatureUnit'.

Please check docs if you need to know more about this param.

**Comment by litinoveweedle** [comment]
Hello, lint run just discovered new issue:

Invalid climate device JSON file '7100.json': operation mode 'on_once' is not defined, but it is used in commands.

Is this something your setup requires?

**Comment by ripa1993** [comment]
@litinoveweedle should be fine now, I renamed `on_once` to `on` and `on` == `off`. 

This device has a single command for both on/off and the status is maintained by the AC unit. If I got it right from `climate.py` if the state is not off, then it should not send the on command again, right? 

Sorry but I blindly copy pasted the device codes from the original repo

**Comment by litinoveweedle** [comment]
Hello, no problem.

Yes, your understanding is fully correct, I made this change from the original implementation to exactly solve this issue based on some users experience when `on` == `off` commands. So you shall be fully fine (at least with beta, which would be hopefully released soon).

**Pull request merged**
