### PR TITLE
Light: changes required to work in current HA

### PR DESCRIPTION
**Pull request by make-all**
- remove `delay` parameter from get_controller call
- don't await async_write_ha_state
- call async_write_ha_state when state is changed to off

### CODE REVIEW

**Comment by make-all** [comment]
These are changes on top of the maintainers changes to #132 to bring it up to date with this version of the integration.

With these changes, my previous set up (based on smartHomeHub/SmartIR#997) is again working on HA 2024.9

**Comment by litinoveweedle** [comment]
Hello, I was briefly checking light [documentation](https://developers.home-assistant.io/docs/core/entity/light/) and I have some doubts about how light.py is reflecting `supported_color_modes`. From the docs, it shall be list of supported modes (from `ColorMode` enum). But you are treating it as a scalar:

```
        if (
            CMD_COLORMODE_COLDER in self._commands
            and CMD_COLORMODE_WARMER in self._commands
        ):
            self._colortemp = self.max_color_temp_kelvin
            self._support_color_mode = ColorMode.COLOR_TEMP

        if CMD_NIGHTLIGHT in self._commands or (
            CMD_BRIGHTNESS_INCREASE in self._commands
            and CMD_BRIGHTNESS_DECREASE in self._commands
        ):
            self._brightness = 100
            self._support_brightness = True
            if self._support_color_mode == ColorMode.UNKNOWN:
                self._support_color_mode = ColorMode.BRIGHTNESS
```

This seems to be as wrong. Can you please explain?

**Comment by make-all** [comment]
Because there is no color bulb support, the supported color modes should be one of COLOR_TEMP, BRIGHTNESS or ONOFF.
Combinations of these do not appear to be valid (HA seems to have an assumption that if color temp is supported brightness is also supported.
Since there is only a possibility of one, I only track one, and it is turned into a list in the supported_color_modes implementation https://github.com/litinoveweedle/SmartIR/blob/lights/custom_components/smartir/light.py#L175

**Comment by litinoveweedle** [comment]
you are correct, I checked te HA implementation and it says that those are mutually exclusive:

```
    ONOFF = "onoff"
    """Must be the only supported mode"""
    BRIGHTNESS = "brightness"
    """Must be the only supported mode"""
    COLOR_TEMP = "color_temp"
```

BTW: I think I saw some LED strips with IR remote, so there are probably some light with RGB support...

I will try to go trough rest of the code to be sure I understand it to be able to maintain it.

**Comment by litinoveweedle** [comment]
I just checked the docs (LIGHT.md) and it will need a bit of overhaul. Please check FAN.md for reference. Would you be please able to do it? Thank you.

**Comment by litinoveweedle** [comment]
I added light support into the READM.md. You do not need to provide LIGHT_CODES.md, as those pages are autogenerated on the merge with master.

**Pull request merged**
