### PR TITLE
Add MSZ-HR35VF

### PR DESCRIPTION
**Pull request by vxav**
There is already MSZ-HR35VF under `1037` but we think there are different codes depending on the remote.
I'm opening a PR here as the main project seems unmaintained.

I propose to add `1141` to the other remote.

Discussed 👇 

- https://github.com/smartHomeHub/SmartIR/pull/981
- https://github.com/smartHomeHub/SmartIR/issues/1272

### CODE REVIEW

**Comment by vxav** [comment]
Ping @litinoveweedle for visibility

**Comment by litinoveweedle** [comment]
Pong @vxav ;-)

I am very well aware of the few opened PR for new codes. The problem is, that I do not like the original way how the codes  PRs are/were handled. So after fixing the integration code (hopefully now done) I need to address this topic as well.

I decided to create automation for checking submitted code files, both for syntax, logic and formatting. This script will be used in the PR workflow to test the CQ. I also need to produce script to automatically amend readme files to update supported devices list. I am not gonna spend my time evaluating each and every PR manually, as I simply don't have enough time. So please be patient I will try to do this ASAP.

**Comment by vxav** [comment]
No worries at all! I wasn't sure if you had notifications set on PRs but it looks like you are working on the right thing 🙂. In the meantime I have it in the `custom_code` folder (which was a great addition btw!).

**Comment by litinoveweedle** [comment]
Hello, as discussed I implemented detailed checks on the all device data files. Would you be please kind to pull updated master, merge it to your branch and re file the PR? Thank you.

**Comment by vxav** [comment]
I rebased and resolved conflicts

**Pull request merged**
