### PR TITLE
Adds support for imperial units

### PR DESCRIPTION
**Pull request by TheAppleFreak**
This change adds in support for supporting and automatically converting between Fahrenheit and Celsius. Using this, you can use SmartIR climate devices in your preferred temperature format, instead of being forced to use Celsius (which can cause issues when other software like Apple Home is expecting the temperatures to be in Fahrenheit already).

This ports over the changes from https://github.com/smartHomeHub/SmartIR/pull/1103, originally made by @devbyaccident and @kevin-brown, with an additional change to stop using a deprecated constant. This is a flaw that has existed in the original project since 2019, and has been reported numerous times over the years (https://github.com/smartHomeHub/SmartIR/issues/29, https://github.com/smartHomeHub/SmartIR/issues/155, https://github.com/smartHomeHub/SmartIR/issues/160, https://github.com/smartHomeHub/SmartIR/issues/669, https://github.com/smartHomeHub/SmartIR/issues/686) with several ignored pull requests to fix this behavior (https://github.com/smartHomeHub/SmartIR/pull/692, https://github.com/smartHomeHub/SmartIR/pull/795, https://github.com/smartHomeHub/SmartIR/pull/1103).

### CODE REVIEW

**Comment by litinoveweedle** [comment]
Hello @TheAppleFreak , than you very much for this PR and sorry for later reply, I missed it. 

It would be very nice to close this issue indeed, but I would rather propose to use HA native temperature converter, something like this should work:

```
 from homeassistant.util.unit_conversion import TemperatureConverter

self._min_temperature = TemperatureConverter.convert(
    self._min_temperature, self._unit, UnitOfTemperature.CELSIUS
)
```

There is also small glitch in your PR, as you convert self._min_temperature only after it is already assigned as default target temperature (which shall be also IMHO internally kept as Celsius)

`self._target_temperature = self._min_temperature`

Also due to recently activated CodeQL checks merge is failing on formatting - please use python black formatter. Would you please mind to correct those issue or shall I?

**Comment by litinoveweedle** [comment]
Two more finding. 

1. Rounding to whole number as originally proposed should not be used, a the result number shall follow precision set in self._precision.
2. It is not possible to use in the send_command conversion the self._target_temperature as input value, as it is not yet set to the requested temperature value (it is only set at the end of the send_command()). It is required to use temperature or target_temperature instead.

```
  target_temperature = "{0:g}".format(temperature)

   if self._unit == UnitOfTemperature.FAHRENHEIT:
                    target_temperature = "{0:g}".format(self._fahrenheit_to_celsius(self._target_temperature))
```

**Comment by litinoveweedle** [comment]
OK, and third probably the most important issue. In the best case, TemperatureUnit set in the HA corresponds with the units used in the device data codes in the .json file. This is then working well without any needs for conversion. Conversion is only required if those units are different. We know HA temperature unit as it is available in:

`self._unit = hass.config.units.temperature_unit`

but we do not explicitly know which temperature unit is used in the device data json file for temperature data:

```
  "minTemperature": 18.0,
  "maxTemperature": 32.0,
....
  "commands": {
    "off": "[3793, -1883, 480, -463, 477, -1410, 479, -461, 479, -1411, 478, -461, 478, -1411, 478, -463, 477, -1411, 477, -464, 476, -1412, 477, -464, 476, -1411, 476, -1412, 477, -464, 477, -1411, 477, -463, 477, -1411, 478, -1411, 477, -1411, 477, -1410, 479, -463, 477, -467, 473, -1410, 479, -1386, 502, -462, 477, -464, 477, -464, 477, -463, 477, -1409, 479, -463, 478, -463, 476, -464, 477, -1411, 477, -1410, 478, -1411, 478, -1409, 479, -462, 478, -463, 478, -463, 477, -463, 478, -1410, 477, -463, 477, -464, 476, -464, 477, -464, 476, -1412, 477, -462, 478, -464, 476, -463, 478, -1409, 479, -462, 477, -465, 477, -463, 477, -1411, 477, -463, 477, -463, 477, -464, 478, -462, 477, -464, 477, -461, 479, -463, 477, -463, 477, -464, 477, -463, 477, -463, 477, -463, 478, -464, 476, -1410, 479, -463, 477, -462, 478, -464, 476, -464, 476, -464, 478, -462, 478, -463, 477, -463, 477, -463, 477, -464, 477, -463, 477, -1410, 479, -461, 478, -464, 476, -464, 477, -462, 479, -463, 477, -462, 478, -464, 476, -463, 478, -462, 478, -1410, 478, -1409, 480, -461, 479, -1410, 477, -1388, 502, -1410, 477, -1411, 478, -1410, 478, -462, 478, -463, 477, -463, 477, -1411, 478, -462, 478, -464, 477, -1410, 478]",
    "auto": {
      "auto": {
        "18": "[
```

IMHO the only proper fix is to add new field for temperatureUnit in the .json and maybe add some logic to try to guess the unit in case it is not declared (backward compatibility)

**Comment by litinoveweedle** [comment]
I did implemented (hopefully) Fahrenheit support in [this branch](https://github.com/litinoveweedle/SmartIR/tree/climate_fahrenheit_support).

As I am not able to test it, could you please? If successfully tested I will merge and release. Thank you.

**Comment by taylorcjensen** [comment]
Would love to bump support for Fahrenheit, I am moving away from the unmaintained https://github.com/smartHomeHub/SmartIR and this was a major pain point there as well (except there the maintainer closed all mention of Fahrenheit without discussion, so thanks for being open to it).

**Pull request closed without merging**
